out_dir = "../conv_out"
formats = ["md", "json"]
tz = "UTC"
date_from = "utc"
dedupe = true
copy_assets = false
pretty_json_indent = 2
filename_from = "title"

[state]
dir = "./.floatctl/state"

[filters]
since = ""
until = ""
